### ISSUE TITLE
Client: UI for sample-size estimation

### ISSUE THREAD

**Issue by vteague** [DemocracyDevelopers/colorado-rla#95]
This can be very simple - in the prototype, it's just one button on a page. It's possibly more elegant to make it one of the menu options in the reports drop-down. Confirm with cdos.

Depends on #72 for actual functioning, though obviously the UI can be built before the endpoint is ready.

**Comment by cjcarlton** [comment]
From Vanessa's e-mail after our meeting on 8/1/24:

There's a little drop-down in the upper left with "define audit" Eddie would like the Estimate Sample Sizes endpoint to be a separate menu item from the Define Audit – give it a separate thread. Could actually have a whole separate flow, which is like the define audit flow and then stops before there's an opportunity to transition to starting the audit. (Under the hood, it would actually be a different view of the same flow – it's fine if it sets the single copy of data including canonicalization data and the risk limit, because the database will be wiped afterwards anyway.)

And zulip:

Hi @Charlie Carlton (guest) after you left there was a bit of discussion about exactly what the estimate-sample-sizes flow might look like. I think we all agreed that there shouldn't really be any need to actually implement an actually separate flow - it should just be a cut-down version of the existing Define Audit flow, but one that remembers not to progress past the estimate-sample-sizes point.

The bare-bones version would be:
A. A separate 'estimate sample sizes' item on the drop-down before 'Define audit'
B. Walk through the audit flow (it's fine if it sets the 'real' audit data), do canonicalization and set the risk limit, etc, generate the assertions, and then do sample size estimation.
C. Stop it (disable or hide the 'next' button) so that it cannot progress to actually starting the audit round. There's no need to enter the seed either.

The slightly-nicer version would be the same, but would hide in the UI the things that aren't relevant to sample-size estimation (e.g. the dates for the ceremonies).

Eddie thinks that he'll need to clear the database after all this and start again, but I'm not sure he will - I run the 'define audit' flow through over and over again, and I don't think there's a problem as long as you don't progress to starting the audit. In short, as long as Eddie doesn't mind the values he has set in "estimate sample sizes" popping up in the "define audit" flow (which should be fine because they should be the same anyway) I think this should all just work.

**Comment by vteague** [comment]
Update: everyone decided this really isn't necessary - the estimate sample sizes button integrated into the main flow is fine. Closing this issue.
